name: Deploy VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.VPS_IP }}" ]; then
            echo "Error: VPS_IP secret is not set."
            exit 1
          fi
          if [ -z "${{ secrets.VPS_USER }}" ]; then
            echo "Error: VPS_USER secret is not set."
            exit 1
          fi
          if [ -z "${{ secrets.VPS_SSH_KEY }}" ]; then
            echo "Error: VPS_SSH_KEY secret is not set."
            exit 1
          fi

      - name: Deploy para VPS
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_IP }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: "/etc/icontainer/apps/openresty/openresty/www/sites/linkinstagram.leolima.digital/index/"
